import Head from 'next/head';
import TopLandingPage from '@/components/top_landing_page/top_landing_page';
import FAQ from '@/components/faq/faq';
import Footer from '@/components/footer/footer';
import Demos from '@/components/demos/demo';
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex w-full flex-col">
        <TopLandingPage />
        <Demos />
        <FAQ />
        <Footer border={'8'} />
      </main>
    </>
  );
}
